### ISSUE TITLE
neptune for Pasta curves

### ISSUE THREAD

**Issue by srinathsetty** [filecoin-project/neptune#128]
The repo currently says: "Neptune is specialized to the [BLS12-381 curve](https://electriccoin.co/blog/new-snark-curve/). Although the API allows for type specialization to other fields, the round numbers, constants, and s-box selection may not be correct. Do not do this."

Can we verify if the same set of constants would work for both curves in the Pasta cycle?

**Comment by porcuquine** [comment]
Yes, it's fine — because like BLS12-381, they are both prime fields of ~256 bits. I believe @DrPeterVanNostrand looked into this specifically and confirmed no change is required. We just didn't update the documentation when adding general support for Pasta curves. @DrPeterVanNostrand Can you confirm?

**Comment by DrPeterVanNostrand** [comment]
Hi @srinathsetty, [`round_numbers.rs`](https://github.com/filecoin-project/neptune/blob/master/src/round_numbers.rs) assumes that the field which Poseidon is instantiated over is ~256 bits (which corresponds to our targeted 128-bit security level). BLS12-381, Pallas, and Vesta each have a 255-bit scalar field, so there's no problem using those fields. There is also an [assertion](https://github.com/filecoin-project/neptune/blob/master/src/round_constants.rs#L35-#L38) when generating round constants which checks that the field size of the `PrimeField` type parameter is 32 bytes.

I think "Neptune is specialized to the BLS12-381 curve" also means that we implement a Groth16 circuit, GPU functionality, and have an audit for BLS12-381's scalar field. The "do not do this" part of the README should probably be made more specific.
