### ISSUE TITLE
wasm target build error

### ISSUE THREAD

**Issue by themighty1** [filecoin-project/neptune#155]
Hi, could you pls suggest the correct way to build this lib for wasm. I tried
`cargo build --target wasm32-unknown-unknown`
and also with
`cargo build --target wasm32-unknown-unknown --features "wasm"`
but was getting compile errors:
 MmapInner::map(self.get_len(file)?, file, self.offset).map(|inner| Mmap { inner: inner })
    |         ^^^^^^^^^ use of undeclared type `MmapInner`

Thanks.

**Comment by porcuquine** [comment]
@samuelburnham might have some insight into this.

**Comment by themighty1** [comment]
Thank you. Solved.
